### ISSUE TITLE
res/values/array.xml

### ISSUE THREAD

**Issue by HTC600** [4455jkjh/Apktool-android#1]
https://github.com/iBotPeaches/Apktool/pull/2000/files
I informed you by email, but you ignored it.  Now report here.  My telegram > https://t.me/SaWSeM

**Comment by HTC600** [comment]
I propose further discussion in the established group.
https://t.me/joinchat/ISArbRAx0BPKW-_imJ265g

**Comment by 4455jkjh** [comment]
thanks
